### ISSUE TITLE
Atualizar critérios para 2024

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/relatoriosOBZ#1]
Mensagems no Teams:

> > [Pedro] temos que avaliar e ajustar o q precisa pra exibirmos CET SEPLAG CAMG corretamente no painel
> 
> [Francisco] Estamos com a parametrização pra receber uma planilha pra cada um, mas CET e CAMG ainda não enviaram. É isso mesmo, correto?
> 
> Sobre a transposição dos valores, estamos usando a lógica do ano passado https://github.com/splor-mg/relatoriosOBZ/blob/main/R/utils.R. 
> 
> Como zeramos a base, precisamos dos critérios válidos para 2024 para que por exemplo os valores da base reestimativa (ie. limite 2024) não fique vazia.
> 
> Confirma também por favor se devemos continuar com a transposição das UOs 1711 e 1721 (e indique ajustes na memória pra 2024 se necessário).

**Comment by fjuniorr** [comment]
## Critério CET 2024

![image](https://github.com/user-attachments/assets/542a2dd3-c9ed-459b-9a99-c68defa5af5b)

## Critério CAMG 2024

![image](https://github.com/user-attachments/assets/e2730556-8786-40d9-a61e-926d628b8f97)

**Comment by carloshob** [comment]
@fjuniorr, no comit [06c8df9](https://github.com/splor-mg/relatoriosOBZ/commit/06c8df9dc9b8e7a28c9a2f94cdab1ca9955fa575) fizemos as alterações solicitadas pelo Pedro. 

No entanto, o @hslinhares levantou que o remapeamento de Unidades somente seria necessário ser aplicado nas bases da execução, e somente na `dados-link-obz-2025`, já que a DCMEFO separaria em planilhas distintas SEPLAG, CAMG e CET. 

Observamos que as ações da CET ainda não foram retiradas da planilha da SEPLAG e colocadas em uma separada.

**Comment by carloshob** [comment]
@fjuniorr, complementando o comentário anterior, entendo que, no intuito de o datapackage `relatoriosOBZ` cumprir o eventual objetivo de conter funções e ferramentas a serem reutilizadas em anos futuros, talvez seja necessário pensarmos tanto em uma estrutura de `critério-ano`, como na parametrização `ano-ref` para orientar como esse critério será aplicado nos diferentes anos das bases (i.e.: execução, reestimativa, obz). 

Por exemplo, pode ser que o critério de transformação/separação da CET e CAMG da UO SEPLAG (chamar de critério "remap-CET-CAMG") seja interessante para o `obz-2025` - e, com isso, eventualmente precisará de parâmetros específicos a depender do ano de cada uma das bases contidas no `obz-2025` - mas talvez o "remap-CET-CAMG" não seja útil quando do `obz-2026`.

Isso me faz pensar que talvez uma das soluções para o problema seja criar diferentes funções para cada um dos critérios/transformações que desejemos fazer, bem como criar uma parametrização "true/false" para cada uma das funções/critérios que desejemos aplicar no projeto em questão (no caso, `obz-2025`).
